@startuml

!define ENUM enum
!define COMPOSITION *--
!define AGGREGATION o--
!define ASSOCIATION -->

skinparam groupInheritance 2

ENUM СтатусКниги {
  Доступна
  Выдана
  Забронирована
}

class Человек {
  + ФИО: string
  + датаРождения: date
  + пол: string
}

class Читатель {
  + статусЗадолженности: boolean
}

class Библиотекарь {
  + списокОбработанныхВыдач: List<ВыдачаКниги>
}

class Администратор {
  + списокУправляемыхОтчётов: List<Отчёт>
}

class Книга {
  + название: string
  + автор: string
  + ISBN: string
  + жанр: string
  + годИздания: int
}

class ЭкземплярКниги {
  + уникальныйИнвентарныйНомер: string
  + статус: СтатусКниги
}

class ВыдачаКниги {
  + датаВыдачи: date
  + датаВозврата: date
}

class Бронирование {
  + датаБронирования: date
  + срокДействия: date
}

class Штраф {
  + сумма: int
  + датаНачисления: date
}

class Отчёт {
  + датаСоздания: date
  + тип: string
}

' Наследование
Человек <|-- Читатель
Человек <|-- Библиотекарь
Библиотекарь <|-- Администратор

' Связи
Книга "1" ASSOCIATION "1..*" ЭкземплярКниги
ЭкземплярКниги "1" ASSOCIATION "0..*" ВыдачаКниги
Читатель "1" ASSOCIATION "0..*" ВыдачаКниги
Библиотекарь "1" ASSOCIATION "0..*" ВыдачаКниги

ЭкземплярКниги "1" ASSOCIATION "0..*" Бронирование
Читатель "1" ASSOCIATION "0..*" Бронирование

Читатель "1" ASSOCIATION "0..*" Штраф

АДМИНИСТРАТОР ||..|| ОТЧЁТ : создаёт
ВыдачаКниги ||..|| Штраф : может иметь

@enduml
